import React, { useState, useEffect, useMemo } from 'react';
import { Line } from 'react-chartjs-2';
import { TrendingUp, Calculator, Clock, ChevronDown, ChevronUp, RefreshCw, Database } from 'lucide-react';
import { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend, Filler } from 'chart.js';

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend, Filler);

// Nepal Custom Duty is 10% (Updated 2026)
const DUTY_RATE = 0.10; 
const BANK_MARGIN = 0.005;
const VAT_RATE = 0.13;
const TOLA_GRAMS = 11.6638;

const App = () => {
  const [prices, setPrices] = useState({ gold: 318800, silver: 7065, lastUpdated: 'Loading...', source: 'Cache' });
  const [activeMetal, setActiveMetal] = useState('gold');
  const [loading, setLoading] = useState(true);
  const [weight, setWeight] = useState({ tola: '', aana: '', lal: '' });
  const [makingCharge, setMakingCharge] = useState('');
  const [showVatBreakdown, setShowVatBreakdown] = useState(false);

  // Simple AD to BS Conversion
  const toBS = (dateStr) => {
    const d = new Date(dateStr || Date.now());
    const year = d.getFullYear() + 56;
    const months = ["Baisakh", "Jestha", "Ashadh", "Shrawan", "Bhadra", "Ashoj", "Kartik", "Mangsir", "Poush", "Magh", "Falgun", "Chaitra"];
    const month = (d.getMonth() + 9) % 12;
    return `${d.getDate()} ${months[month]} ${year}`;
  };

  const fetchPrices = async () => {
    setLoading(true);
    try {
      // Fetch the JSON file generated by your Python scraper
      const response = await fetch('https://raw.githubusercontent.com/Timeswantstocode/GoldView/main/data.json');
      const data = await response.json();
      setPrices({
        gold: data.gold,
        silver: data.silver,
        lastUpdated: toBS(data.date),
        source: data.source
      });
    } catch (err) {
      // Dynamic Fallback Math: (Intl Spot * 1.10 Duty * 1.005 Margin)
      const res = await fetch(`https://api.metalpriceapi.com/v1/latest?api_key=27882472c556bcacfdfb6062bb99771d&base=NPR&currencies=XAU,XAG`);
      const apiData = await res.json();
      const calc = (spot) => Math.round((spot / 31.1035) * TOLA_GRAMS * (1 + DUTY_RATE) * (1 + BANK_MARGIN));
      setPrices({
        gold: calc(apiData.rates.NPRXAU),
        silver: calc(apiData.rates.NPRXAG),
        lastUpdated: toBS(),
        source: "API (10% Duty Adjusted)"
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchPrices(); }, []);

  const calculation = useMemo(() => {
    const rate = activeMetal === 'gold' ? prices.gold : prices.silver;
    const totalTola = Number(weight.tola || 0) + (Number(weight.aana || 0) / 16) + (Number(weight.lal || 0) / 100);
    const subtotal = (totalTola * rate) + Number(makingCharge || 0);
    return { totalTola, vatAmount: subtotal * VAT_RATE, grandTotal: subtotal * (1 + VAT_RATE) };
  }, [weight, makingCharge, prices, activeMetal]);

  const chartData = {
    labels: ['25 Magh', '26 Magh', '27 Magh', '28 Magh', '29 Magh', '30 Magh', 'Today'],
    datasets: [{
      data: activeMetal === 'gold' 
        ? [309300, 312000, 315000, 339300, 318800, 318800, prices.gold]
        : [6870, 6950, 7100, 7505, 7065, 7065, prices.silver],
      fill: true,
      borderColor: activeMetal === 'gold' ? '#EAB308' : '#94A3B8',
      backgroundColor: activeMetal === 'gold' ? 'rgba(234, 179, 8, 0.1)' : 'rgba(148, 163, 184, 0.1)',
      tension: 0.4,
      pointRadius: 6,
      pointHoverRadius: 12,
    }]
  };

  return (
    <div className="min-h-screen bg-[#050505] text-slate-300 font-sans p-4 md:p-10">
      <header className="max-w-6xl mx-auto flex flex-col md:flex-row justify-between items-center mb-10 gap-6 border-b border-white/5 pb-8">
        <div className="text-center md:text-left">
          <h1 className="text-5xl font-black tracking-tighter text-white uppercase italic">
            GOLD<span className="text-yellow-500">VIEW</span>
          </h1>
          <p className="text-slate-500 text-[10px] mt-2 font-bold uppercase tracking-[0.3em]">
            <Database size={10} className="inline mr-2 text-green-500" /> {prices.source} • {prices.lastUpdated}
          </p>
        </div>
        <button onClick={fetchPrices} className="p-4 bg-white/5 rounded-2xl hover:bg-yellow-500 hover:text-black transition-all">
          <RefreshCw size={20} className={loading ? "animate-spin" : ""} />
        </button>
      </header>

      <main className="max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Price Cards */}
        <div className="lg:col-span-8 space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <button onClick={() => setActiveMetal('gold')} className={`p-10 rounded-[2.5rem] text-left transition-all border-2 ${activeMetal === 'gold' ? 'border-yellow-500 bg-yellow-500/5' : 'border-white/5 opacity-40'}`}>
              <p className="text-[10px] font-black text-yellow-500 uppercase mb-2">24K Fine Gold</p>
              <h2 className="text-5xl font-black text-white tracking-tighter">Rs. {prices.gold.toLocaleString()}</h2>
            </button>
            <button onClick={() => setActiveMetal('silver')} className={`p-10 rounded-[2.5rem] text-left transition-all border-2 ${activeMetal === 'silver' ? 'border-slate-400 bg-slate-400/5' : 'border-white/5 opacity-40'}`}>
              <p className="text-[10px] font-black text-slate-400 uppercase mb-2">Pure Silver</p>
              <h2 className="text-5xl font-black text-white tracking-tighter">Rs. {prices.silver.toLocaleString()}</h2>
            </button>
          </div>

          {/* Interactive Graph */}
          <div className="bg-white/5 border border-white/10 p-8 rounded-[3rem] h-[400px]">
            <Line data={chartData} options={{
              responsive: true, maintainAspectRatio: false,
              plugins: { legend: { display: false }, tooltip: { backgroundColor: '#000', padding: 15, callbacks: { label: (ctx) => `Price: Rs. ${ctx.parsed.y.toLocaleString()}` } } },
              scales: { y: { display: false }, x: { grid: { display: false }, border: { display: false } } }
            }} />
          </div>
        </div>

        {/* Calculator */}
        <div className="lg:col-span-4">
          <div className="bg-[#0c0c0c] border border-white/10 p-10 rounded-[3rem] shadow-2xl">
            <h3 className="text-[11px] font-black mb-8 text-white uppercase tracking-widest flex items-center">
              <Calculator size={16} className="mr-3 text-yellow-500" /> Gold/Silver Price Calculator
            </h3>
            <div className="space-y-6">
              <div className="grid grid-cols-3 gap-2">
                {['tola', 'aana', 'lal'].map(u => (
                  <div key={u}>
                    <label className="text-[9px] uppercase font-bold text-slate-600 block mb-2">{u}</label>
                    <input type="number" value={weight[u]} onChange={e => setWeight({...weight, [u]: e.target.value})} className="w-full bg-white/5 border border-white/10 rounded-xl p-4 text-white outline-none focus:border-yellow-500" />
                  </div>
                ))}
              </div>
              <input type="number" placeholder="Making Charges" value={makingCharge} onChange={e => setMakingCharge(e.target.value)} className="w-full bg-white/5 border border-white/10 rounded-xl p-4 text-white outline-none focus:border-yellow-500" />
              <div className="pt-6 border-t border-white/10">
                <p className="text-[10px] uppercase font-bold text-slate-500">Total Settlement</p>
                <h2 className="text-5xl font-black text-white tracking-tighter">Rs. {Math.round(calculation.grandTotal).toLocaleString()}</h2>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default App;
